package io.github.takahirom.arbigent.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.CliktError
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.option
import java.io.File
import java.net.HttpURLConnection
import java.net.URI
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.util.Properties

private const val WRAPPER_SCRIPT_NAME = "arbigentw"
/** Read by the script from its own directory, so the two files always travel together. */
private const val WRAPPER_PROPERTIES_PATH = "arbigentw.properties"
/** Where arbigent 0.81.0 wrote the properties. Removed when the wrapper is regenerated. */
private const val LEGACY_WRAPPER_PROPERTIES_PATH = ".arbigent/wrapper/arbigent-wrapper.properties"
private const val RELEASE_BASE_URL = "https://github.com/takahirom/arbigent/releases/download"

private val SHA256_PATTERN = Regex("^[0-9a-f]{64}$")

private const val CONNECT_TIMEOUT_MS = 30_000
private const val READ_TIMEOUT_MS = 60_000
private const val MAX_REDIRECTS = 5

/** Hosts the checksum may be read from without encryption, because nothing can sit in between. */
private val LOOPBACK_HOSTS = setOf("127.0.0.1", "localhost", "::1", "[::1]")

/**
 * Reads the version this CLI was built from. Generated by the `generateVersionProperties`
 * Gradle task into the CLI resources.
 */
internal fun arbigentCliVersion(): String? =
  ArbigentWrapperCommand::class.java.getResourceAsStream("/arbigent-cli-version.properties")
    ?.use { stream -> Properties().apply { load(stream) }.getProperty("version") }
    ?.takeIf { it.isNotBlank() }

internal fun distributionUrlFor(version: String): String =
  "$RELEASE_BASE_URL/$version/arbigent-$version.tar.gz"

/**
 * A version is publishable only if a matching GitHub release exists. Versions produced by
 * `git describe` on an untagged commit (`0.80.0-31-gfe9e157`, `...dirty`) have no release
 * and therefore no distribution to point the wrapper at.
 */
internal fun isReleaseVersion(version: String): Boolean =
  Regex("^[0-9]+\\.[0-9]+\\.[0-9]+(-[A-Za-z0-9.]+)?$").matches(version) &&
    !version.contains(".dirty") &&
    !Regex("-[0-9]+-g[0-9a-f]+").containsMatchIn(version)

/**
 * Writes a `arbigentw` shell wrapper and its properties file into a repository so that
 * contributors and CI can run arbigent without installing it first, the way `gradlew` works.
 */
class ArbigentWrapperCommand : CliktCommand(name = "wrapper") {
  private val version by option(
    "--version",
    help = "Arbigent release to pin. Defaults to the version of this CLI.",
  )
  private val distributionUrl by option(
    "--distribution-url",
    help = "Distribution archive URL. Defaults to the GitHub release tarball for --version.",
  )
  private val sha256 by option(
    "--sha256",
    help = "SHA-256 of the distribution archive. Defaults to the '.sha256' file next to it.",
  )
  private val directory by option(
    "--dir",
    help = "Directory the wrapper is written to. Defaults to the current directory.",
  )

  override fun help(context: Context): String =
    "Generate the arbigentw wrapper script that downloads and runs a pinned arbigent release"

  override fun run() {
    val resolvedVersion = version ?: arbigentCliVersion()
    ?: throw CliktError("Cannot determine the arbigent version. Pass --version <version>.")
    if (version == null && !isReleaseVersion(resolvedVersion)) {
      throw CliktError(
        "This CLI reports version '$resolvedVersion', which is not a published release. " +
          "Pass --version <version> to pin a released version."
      )
    }
    val url = distributionUrl ?: distributionUrlFor(resolvedVersion)
    val checksum = sha256 ?: fetchChecksum(url)
    if (!SHA256_PATTERN.matches(checksum)) {
      throw CliktError("'$checksum' is not a lowercase hex SHA-256 digest.")
    }

    // toRealPath resolves the symlinks the caller chose to point at; the components below are the
    // ones nobody asked for.
    val root = Files.createDirectories(File(directory ?: ".").toPath()).toRealPath()
    writeInto(root, WRAPPER_SCRIPT_NAME, wrapperScript(), executable = true)
    writeInto(
      root,
      WRAPPER_PROPERTIES_PATH,
      buildString {
        appendLine("distributionVersion=$resolvedVersion")
        appendLine("distributionUrl=$url")
        appendLine("distributionSha256Sum=$checksum")
      }.toByteArray(),
      executable = false,
    )
    removeLegacyProperties(root)
  }

  /**
   * Deletes the properties file an earlier release wrote under `.arbigent/wrapper`, since the
   * script no longer reads it and a stale copy would only mislead. The directories are removed
   * only when the file was the last thing in them: `.arbigent` also holds project settings.
   */
  private fun removeLegacyProperties(root: Path) {
    val legacy = root.resolve(LEGACY_WRAPPER_PROPERTIES_PATH)
    val components = generateSequence(legacy) { it.parent }.takeWhile { it != root }.toList()
    // A link among the components would make the delete reach outside the wrapper directory,
    // so the file is reported instead of removed.
    if (components.any { Files.isSymbolicLink(it) }) {
      if (Files.exists(legacy)) {
        echo("$legacy is no longer read; it is reached through a symbolic link, so remove it yourself.", err = true)
      }
      return
    }
    if (!Files.deleteIfExists(legacy)) return
    echo("Removed $legacy, which the wrapper no longer reads")
    for (directory in components.drop(1)) {
      val empty = Files.list(directory).use { it.findAny().isEmpty }
      if (!empty) break
      Files.delete(directory)
      echo("Removed empty $directory")
    }
  }

  private fun fetchChecksum(url: String): String {
    val checksumUrl = "$url.sha256"
    val body = try {
      read(URI(checksumUrl))
    } catch (e: CliktError) {
      throw e
    } catch (e: Exception) {
      throw CliktError("Cannot read $checksumUrl (${e.message}). Pass --sha256 <digest> instead.")
    }
    // The published file holds the bare digest, but 'sha256sum' output carries a filename too.
    return body.trim().substringBefore(' ').lowercase()
  }

  /**
   * Reads the digest over a connection nobody can rewrite. The digest is the only thing that says
   * which bytes the wrapper may install, so an attacker who can replace it can replace the whole
   * distribution: the first hop must be HTTPS, every redirect must stay on HTTPS, and plain HTTP is
   * accepted only against the loopback interface, where there is nothing in between.
   */
  private fun read(start: URI): String {
    var uri = start
    repeat(MAX_REDIRECTS + 1) { hop ->
      requireTrustedUrl(uri, firstHop = hop == 0)
      val connection = uri.toURL().openConnection() as HttpURLConnection
      connection.instanceFollowRedirects = false
      connection.connectTimeout = CONNECT_TIMEOUT_MS
      connection.readTimeout = READ_TIMEOUT_MS
      try {
        val code = connection.responseCode
        if (code !in 300..399) {
          if (code != HttpURLConnection.HTTP_OK) {
            throw CliktError("$uri answered HTTP $code. Pass --sha256 <digest> instead.")
          }
          return connection.inputStream.use { it.readBytes().decodeToString() }
        }
        val location = connection.getHeaderField("Location")
          ?: throw CliktError("$uri answered HTTP $code without a Location header.")
        // A Location may be relative to the URL it came from.
        uri = uri.resolve(location)
      } finally {
        connection.disconnect()
      }
    }
    throw CliktError("$start redirects more than $MAX_REDIRECTS times.")
  }

  private fun requireTrustedUrl(uri: URI, firstHop: Boolean) {
    val scheme = uri.scheme?.lowercase()
    if (scheme == "https") return
    if (firstHop && scheme == "http" && uri.host?.lowercase() in LOOPBACK_HOSTS) return
    throw CliktError(
      "Refusing to read the checksum from $uri: it must be served over HTTPS. " +
        "Pass --sha256 <digest> instead."
    )
  }

  private fun wrapperScript(): ByteArray =
    javaClass.getResourceAsStream("/$WRAPPER_SCRIPT_NAME")
      ?.use { it.readBytes() }
      ?: throw CliktError("The $WRAPPER_SCRIPT_NAME template is missing from this distribution.")

  private fun writeInto(root: Path, relative: String, bytes: ByteArray, executable: Boolean) {
    val target = root.resolve(relative)
    createRealDirectories(root, target.parent)
    if (Files.isSymbolicLink(target)) {
      throw CliktError("$target is a symbolic link. Remove it and run this again.")
    }
    val staged = Files.createTempFile(target.parent, ".${target.fileName}", ".tmp")
    try {
      Files.write(staged, bytes)
      // The executable bit does not survive packaging into the jar, and it is set before the rename
      // so the published file is never briefly there without it.
      if (executable) staged.toFile().setExecutable(true, false)
      publish(staged, target)
    } finally {
      Files.deleteIfExists(staged)
    }
    echo("Wrote $target")
  }

  private fun publish(staged: Path, target: Path) {
    try {
      Files.move(staged, target, StandardCopyOption.ATOMIC_MOVE)
    } catch (atomicFailure: AtomicMoveNotSupportedException) {
      try {
        Files.move(staged, target, StandardCopyOption.REPLACE_EXISTING)
      } catch (failure: Exception) {
        failure.addSuppressed(atomicFailure)
        throw failure
      }
    }
  }

  /**
   * Creates the directories the wrapper needs under [root]. A symbolic link among them would send
   * the wrapper somewhere the caller never named, and the rename that publishes it would follow the
   * link, so a link is refused rather than replaced.
   */
  private fun createRealDirectories(root: Path, directory: Path) {
    val components = generateSequence(directory) { it.parent }
      .takeWhile { it != root }
      .toList()
      .asReversed()
    for (component in components) {
      if (Files.isSymbolicLink(component)) {
        throw CliktError("$component is a symbolic link. Remove it and run this again.")
      }
      if (!Files.exists(component)) {
        Files.createDirectory(component)
      } else if (!Files.isDirectory(component)) {
        throw CliktError("$component is not a directory.")
      }
    }
  }
}
