package io.github.takahirom.arbigent.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.CliktError
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.option
import java.io.File
import java.net.URI
import java.util.Properties

private const val WRAPPER_SCRIPT_NAME = "arbigentw"
private const val WRAPPER_PROPERTIES_PATH = ".arbigent/wrapper/arbigent-wrapper.properties"
private const val RELEASE_BASE_URL = "https://github.com/takahirom/arbigent/releases/download"

private val SHA256_PATTERN = Regex("^[0-9a-f]{64}$")

/**
 * Reads the version this CLI was built from. Generated by the `generateVersionProperties`
 * Gradle task into the CLI resources.
 */
internal fun arbigentCliVersion(): String? =
  ArbigentWrapperCommand::class.java.getResourceAsStream("/arbigent-cli-version.properties")
    ?.use { stream -> Properties().apply { load(stream) }.getProperty("version") }
    ?.takeIf { it.isNotBlank() }

internal fun distributionUrlFor(version: String): String =
  "$RELEASE_BASE_URL/$version/arbigent-$version.tar.gz"

/**
 * A version is publishable only if a matching GitHub release exists. Versions produced by
 * `git describe` on an untagged commit (`0.80.0-31-gfe9e157`, `...dirty`) have no release
 * and therefore no distribution to point the wrapper at.
 */
internal fun isReleaseVersion(version: String): Boolean =
  Regex("^[0-9]+\\.[0-9]+\\.[0-9]+(-[A-Za-z0-9.]+)?$").matches(version) &&
    !version.contains(".dirty") &&
    !Regex("-[0-9]+-g[0-9a-f]+").containsMatchIn(version)

/**
 * Writes a `arbigentw` shell wrapper and its properties file into a repository so that
 * contributors and CI can run arbigent without installing it first, the way `gradlew` works.
 */
class ArbigentWrapperCommand : CliktCommand(name = "wrapper") {
  private val version by option(
    "--version",
    help = "Arbigent release to pin. Defaults to the version of this CLI.",
  )
  private val distributionUrl by option(
    "--distribution-url",
    help = "Distribution archive URL. Defaults to the GitHub release tarball for --version.",
  )
  private val sha256 by option(
    "--sha256",
    help = "SHA-256 of the distribution archive. Defaults to the '.sha256' file next to it.",
  )
  private val directory by option(
    "--dir",
    help = "Directory the wrapper is written to. Defaults to the current directory.",
  )

  override fun help(context: Context): String =
    "Generate the arbigentw wrapper script that downloads and runs a pinned arbigent release"

  override fun run() {
    val resolvedVersion = version ?: arbigentCliVersion()
    ?: throw CliktError("Cannot determine the arbigent version. Pass --version <version>.")
    if (version == null && !isReleaseVersion(resolvedVersion)) {
      throw CliktError(
        "This CLI reports version '$resolvedVersion', which is not a published release. " +
          "Pass --version <version> to pin a released version."
      )
    }
    val url = distributionUrl ?: distributionUrlFor(resolvedVersion)
    val checksum = sha256 ?: fetchChecksum(url)
    if (!SHA256_PATTERN.matches(checksum)) {
      throw CliktError("'$checksum' is not a lowercase hex SHA-256 digest.")
    }

    val root = File(directory ?: ".")
    writeScript(File(root, WRAPPER_SCRIPT_NAME))
    writeProperties(File(root, WRAPPER_PROPERTIES_PATH), resolvedVersion, url, checksum)
  }

  private fun fetchChecksum(url: String): String {
    val checksumUrl = "$url.sha256"
    val body = try {
      URI(checksumUrl).toURL().openStream().use { it.readBytes().decodeToString() }
    } catch (e: Exception) {
      throw CliktError("Cannot read $checksumUrl (${e.message}). Pass --sha256 <digest> instead.")
    }
    // The published file holds the bare digest, but 'sha256sum' output carries a filename too.
    return body.trim().substringBefore(' ').lowercase()
  }

  private fun writeScript(target: File) {
    val script = javaClass.getResourceAsStream("/$WRAPPER_SCRIPT_NAME")
      ?.use { it.readBytes() }
      ?: throw CliktError("The $WRAPPER_SCRIPT_NAME template is missing from this distribution.")
    target.parentFile?.mkdirs()
    target.writeBytes(script)
    // The executable bit does not survive packaging into the jar.
    target.setExecutable(true, false)
    echo("Wrote ${target.path}")
  }

  private fun writeProperties(target: File, version: String, url: String, checksum: String) {
    target.parentFile?.mkdirs()
    target.writeText(
      buildString {
        appendLine("distributionVersion=$version")
        appendLine("distributionUrl=$url")
        appendLine("distributionSha256Sum=$checksum")
      }
    )
    echo("Wrote ${target.path}")
  }
}
